apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin
  labels:
    app: php
spec:
  containers:
  - name: phpmyadmin
    image: phpmyadmin:latest

    env:
      - name: PMA_HOST
        value: mysql-service

    ports:
      - containerPort: 80
