apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesbonlegumesbio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesbonlegumesbio
  template:
    metadata:
      labels:
        app: mesbonlegumesbio
    spec:
      containers:
        - name: mesbonlegumesbio
          image: ynov31/nginx-mesbonlegumesbio:latest
          ports:
            - containerPort: 80
