
# Utilisation de l'image officielle Nginx
FROM nginx:latest

# Suppression des fichiers HTML par défaut de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copie du fichier index.html du magasin dans le répertoire de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Exposition du port 80 pour accéder au site web
EXPOSE 80

